# Generated by Django 5.1 on 2024-10-15 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('cxl', 'Chưa Xử Lý'), ('dxl', 'Đã Xử Lý'), ('dcbh', 'Đang Chuẩn Bị Hàng'), ('dgh', 'Đang Giao Hàng'), ('dghh', 'Đã Giao Hàng'), ('khh', 'Khách Hàng Hủy'), ('adh', 'Admin Hủy'), ('dtt', 'Đã thanh toán')], default='cxl', max_length=25)),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi giao hàng'), ('ppl', 'Thanh toán qua paypal')], default='cod', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn Hàng',
                'verbose_name_plural': 'Đơn Hàng',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Chi Tiết Đơn Hàng',
                'verbose_name_plural': 'Chi Tiết Đơn Hàng',
            },
        ),
    ]
