# Generated by Django 5.1 on 2025-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderdetail_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi giao hàng'), ('ppl', 'Thanh toán qua PayPal')], default='cod', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cxl', 'Chưa Xử Lý'), ('dcbh', 'Đang Chuẩn Bị Hàng'), ('dgh', 'Đang Giao Hàng'), ('dghh', 'Đã Giao Hàng'), ('khh', 'Khách Hàng Hủy'), ('adh', 'Admin Hủy'), ('dtt', 'Đã thanh toán')], default='cxl', max_length=25),
        ),
    ]
