# Generated by Django 5.1 on 2025-04-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_paypal_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_order_id',
        ),
    ]
