# Generated by Django 5.1 on 2024-08-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Liên Hệ',
                'verbose_name_plural': 'Liên Hệ',
            },
        ),
    ]
