# Generated by Django 5.1 on 2025-06-12 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_addressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và theo sau là 9 chữ số.', regex='^0[0-9]{9}$')]),
        ),
    ]
