# Generated by Django 5.1 on 2025-05-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='show',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
