# Generated by Django 5.1 on 2024-08-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='show',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='show',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
