# Generated by Django 5.1 on 2025-05-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_flash_sale_end_product_flash_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
