# Generated by Django 5.1 on 2025-06-13 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Combo Món Ăn',
                'verbose_name_plural': 'Combo Món Ăn',
            },
        ),
        migrations.CreateModel(
            name='ProductComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.productcombo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product')),
            ],
            options={
                'verbose_name': 'Món Ăn Trong Combo',
                'verbose_name_plural': 'Món Ăn Trong Combo',
            },
        ),
    ]
